import { useEffect, useMemo, useState } from 'react'
import { BriefcaseBusiness, CalendarClock, ExternalLink, Globe2, Link, MapPin, RefreshCcw, Search, ShieldCheck, Target, Zap } from 'lucide-react'
const accounts=[{name:'LinkedIn Jobs',url:'https://www.linkedin.com/jobs/',icon:Link},{name:'Naukri Jobs',url:'https://www.naukri.com/',icon:BriefcaseBusiness},{name:'Indeed Jobs',url:'https://in.indeed.com/',icon:Globe2},{name:'GitHub Tracker',url:'https://github.com/danielgladson55-lab/Job-tracker',icon:ShieldCheck}]
const regions=['All','Chennai','Bengaluru','India Remote','Global Remote','Other']
function App(){const[jobs,setJobs]=useState([]),[query,setQuery]=useState(''),[region,setRegion]=useState('All'),[minimum,setMinimum]=useState(65),[updated,setUpdated]=useState(''),[error,setError]=useState('')
 const load=async()=>{try{setError('');const r=await fetch(`${import.meta.env.BASE_URL}jobs.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();setJobs(Array.isArray(data)?data:[]);setUpdated(new Date().toLocaleString())}catch(e){setError(e.message)}}
 useEffect(()=>{load();const id=setInterval(load,300000);return()=>clearInterval(id)},[])
 const breaking=useMemo(()=>jobs.filter(j=>j.active!==false&&j.status==='New'&&Number(j.score)>=75).slice(0,10),[jobs])
 const filtered=useMemo(()=>jobs.filter(j=>j.active!==false&&`${j.company} ${j.title} ${j.location} ${(j.skills||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())&&(region==='All'||j.region===region)&&Number(j.score)>=minimum).sort((a,b)=>Number(b.score)-Number(a.score)||new Date(b.first_seen_at)-new Date(a.first_seen_at)),[jobs,query,region,minimum])
 return <><header><div className="wrap nav"><b>DG · Live Job Intelligence</b><span>{updated?`Updated ${updated}`:'Synchronizing…'} <button onClick={load}><RefreshCcw size={15}/>Refresh</button></span></div></header><main className="wrap">
 <section className="hero"><div><em>OFFICIAL CAREER PORTAL MONITOR</em><h1>Live Technology Risk opportunities.</h1><p>New roles appear like a breaking-news feed, with verified source URLs and direct application links.</p></div><div className="metrics"><Metric n={jobs.filter(j=>j.active!==false).length} t="Active"/><Metric n={breaking.length} t="New priority"/><Metric n={filtered.length} t="Visible"/></div></section>
 <section className="ticker"><strong><Zap size={16}/>JOB FLASH</strong><div>{breaking.length?breaking.map(j=><a key={j.id} href={j.apply_url||j.url} target="_blank" rel="noreferrer">NEW · {j.title} · {j.company} · {j.location} · {j.score}% ↗</a>):<span>No new 75+ matches in the current feed.</span>}</div></section>
 <section><h2>Job-hunting accounts</h2><div className="accounts">{accounts.map(({name,url,icon:Icon})=><a href={url} target="_blank" rel="noreferrer" key={name}><Icon/>{name}<ExternalLink size={14}/></a>)}</div></section>
 <section><h2>Opportunity feed</h2><div className="filters"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search role, company or skill"/></label><select value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(x=><option key={x}>{x}</option>)}</select><select value={minimum} onChange={e=>setMinimum(Number(e.target.value))}><option value="0">Any score</option><option value="65">65+ match</option><option value="75">75+ match</option><option value="85">85+ match</option></select></div>{error&&<div className="alert">Feed unavailable: {error}</div>}<div className="jobs">{filtered.map(j=><Job key={`${j.id}-${j.url}`} job={j}/>)}{!error&&!filtered.length&&<div className="empty">No active jobs match the current filters.</div>}</div></section>
 </main><footer>Verify every vacancy on the official employer page before applying.</footer></>}
function Metric({n,t}){return <div><b>{n}</b><span>{t}</span></div>}
function Job({job:j}){return <article className="job"><div className="top"><span className={`badge ${j.status==='New'?'new':''}`}>{j.status||'Active'}</span><b>{j.score}% MATCH</b></div><small>{j.source_platform||j.source} · Job ID: {j.external_job_id||j.id}</small><h3>{j.title}</h3><h4>{j.company}</h4><div className="meta"><span><MapPin size={14}/>{j.location}</span><span><CalendarClock size={14}/>{j.published_at||j.first_seen_at}</span><span><Target size={14}/>{j.resume}</span></div><p>{(j.description||'').slice(0,280)}{(j.description||'').length>280?'…':''}</p><div className="tags">{(j.skills||[]).map(x=><span key={x}>{x}</span>)}</div><a className="apply" href={j.apply_url||j.url} target="_blank" rel="noreferrer">View & Apply <ExternalLink size={15}/></a></article>}
export default App
